### ISSUE TITLE
Create Homepage Layout

### ISSUE THREAD

**Issue by Sabeer-Junaid** [Sabeer-Junaid/quotify#3]
Design the layout of the homepage including sections for displaying quotes, buttons, and other elements.
Attached is a design mockup created for planning the layout and elements of the homepage.

![Home (2)](https://github.com/Sabeer-Junaid/quotify/assets/59570904/afd63b3c-76fa-4cb7-9d94-2a08851d0b70)

**Comment by Sbiswas001** [comment]
Working on it

**Comment by Sabeer-Junaid** [comment]
Thank you for taking this on! Looking forward to seeing your progress.
