### ISSUE TITLE
Fix overall Styling

### ISSUE THREAD

**Issue by Sabeer-Junaid** [Sabeer-Junaid/quotify#5]
This is the current Design

![Screenshot 2024-06-02 8 24 28 PM](https://github.com/Sabeer-Junaid/quotify/assets/59570904/91df69ad-3964-4111-995a-39600aa55727)

Output I need:

![Home (2)](https://github.com/Sabeer-Junaid/quotify/assets/59570904/ef4f341a-3e5a-4566-8bb9-9a704b388682)

Issues:

- [x] Fix Alignment
- [x] Fix Font
- [x] Fix Icons
- [x] Add Logo

**Comment by Vasilistaxo** [comment]
> This is the current Design
> 
> ![Screenshot 2024-06-02 8 24 28 PM](https://private-user-images.githubusercontent.com/59570904/335877666-91df69ad-3964-4111-995a-39600aa55727.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MTg2NzQsIm5iZiI6MTcxNzQxODM3NCwicGF0aCI6Ii81OTU3MDkwNC8zMzU4Nzc2NjYtOTFkZjY5YWQtMzk2NC00MTExLTk5NWEtMzk2MDBhYTU1NzI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDEyMzkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYzA1YmI4MGEzN2UyZDIyMWQ3MzNiNWY0NzExMDlkZDEyZjYxOWQwNGQwZTAwNDZmODczMzBlODY2ZTM0NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V0jzyku-_mtSi2f30FazD_MeFW_icZat1a9RpVzeHGU)
> 
> Output I need:
> 
> ![Home (2)](https://private-user-images.githubusercontent.com/59570904/335877712-ef4f341a-3e5a-4566-8bb9-9a704b388682.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MTg2NzQsIm5iZiI6MTcxNzQxODM3NCwicGF0aCI6Ii81OTU3MDkwNC8zMzU4Nzc3MTItZWY0ZjM0MWEtM2U1YS00NTY2LThiYjktOWE3MDRiMzg4NjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDEyMzkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYmVhNjFjNTU5OGNmZjhlNTRmZTE5NjQ4MDM5Nzk0ZGIzNmJiNjQwODE0NzRjYTA2YWUxODNhMjNlOGMzNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JgCAq-nenJXxF5rP9dLuVr0i96QWlHcSnbJSW-sTYhQ)
> 
> Issues:
> 
> * [x]  Fix Alignment
> * [x]  Fix Font
> * [x]  Fix Icons
> * [x]  Add Logo

I could fix the rest of the tasks if you would assign them to me. Thank you!

**Comment by Sabeer-Junaid** [comment]
thank you for offering to help. but I've almost completed the changes and will be committing them shortly.

**Comment by Vasilistaxo** [comment]
Sure! If i can ever be of any help, id be glad to do so.
